services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
    ports:
      # The HTTP Port
      - "443:443"
      - "80:80"
    volumes:
      # So that Traefik can listen to Docker events
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  portfolio-prod:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ghcr.io/iataand/portfolio-prod:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio-prod.rule=Host(`andrei-iatan.com`)"
      - "com.centurylinklabs.watchtower.enable=true"
