services:
  portfolio-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    working_dir: /app
    command: "npm run dev"  # Start the development server
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge
